import requests
import base64
import pandas as pd
import streamlit as st
import smtplib
from email.mime.text import MIMEText
from datetime import datetime

st.title("RISK ANALYSIS")
st.subheader("Your scanned results can be seen here")


end_url = st.sidebar.text_input("Enter a URL to analyse")
api_key = st.sidebar.text_input("Enter your API Key", type="password")

if not end_url:
    st.warning("Enter a url to proceed")
    st.stop()

if not api_key:
    st.warning("⚠️ Please enter your API key to proceed.")
    st.stop()

st.success("Inputs received!")

BASE_URL = "https://www.virustotal.com/api/v3"
headers = {"x-apikey": api_key}


def send_email(target, label, score, stats):
    sender = "YOUR EMAIL"
    receiver = "RECEIVER EMAIL"
    password = "YOUR EMAIL APP PASSWORD"

    subject = f"[SCAN RESULT] {label} - {target}"

    html = f"""
    <h2>Scan Report</h2>

    <p><b>Target URL:</b> {target}</p>
    <p><b>Status:</b> {label}</p>
    <p><b>Risk Score:</b> {score}%</p>
    <p><b>Scan Time:</b> {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</p>

    <h3>Detection Summary</h3>
    <table border="1" cellpadding="5">
    <tr><th>Category</th><th>Count</th></tr>
    """

    for k, v in stats.items():
        html += f"<tr><td>{k}</td><td>{v}</td></tr>"

    html += """
    </table>

    <h3>Recommendation</h3>
    <p>Review the scan results and avoid interacting with suspicious or malicious URLs.</p>

    <hr>
    <p style="font-size:12px;color:gray;">
    This is an automated report generated by the Risk Analysis System.
    </p>
    """

    msg = MIMEText(html, "html")
    msg["Subject"] = subject
    msg["From"] = sender
    msg["To"] = receiver

    try:
        server = smtplib.SMTP("smtp.gmail.com", 587)
        server.starttls()
        server.login(sender, password)
        server.send_message(msg)
        server.quit()
        st.success("📧 Email report sent successfully")
        st.balloons()
    except Exception as e:
        st.error(f"Email failed: {e}")




def get_data(endpoint):
    url = f"{BASE_URL}/{endpoint}"
    try:
        response = requests.get(url, headers=headers, timeout=10)
        if response.status_code != 200:
            st.error(f"Error: {response.status_code}")
            return None
        return response.json()
    except Exception as e:
        st.error(f"Connection Error: {e}")
        return None




def calculate_confidence(stats):
    malicious = stats.get("malicious", 0)
    total = sum(stats.values())

    if total == 0:
        return "Unknown", 0

    score = malicious / total

    if score == 0:
        label = "Safe"
    elif score < 0.25:
        label = "Suspicious"
    else:
        label = "Malicious"

    return label, round(score * 100, 2)




def analyze_url():
    url_bytes = end_url.encode("utf-8")
    encoded_url = base64.urlsafe_b64encode(url_bytes).decode("utf-8").strip("=")

    data = get_data(f"urls/{encoded_url}")

    if not data:
        return None

    stats = data["data"]["attributes"].get("last_analysis_stats", {})
    return stats



if st.button("Analyze URL"):
    stats = analyze_url()
    if stats:
        st.session_state["stats"] = stats



if "stats" in st.session_state:

    stats = st.session_state["stats"]
    label, score = calculate_confidence(stats)

    st.subheader("🔍 URL Analysis Result")
    st.metric("Verdict", label)
    st.metric("Risk Score (%)", score)

    df = pd.DataFrame(list(stats.items()), columns=["Category", "Count"])

    
    option = st.selectbox(
        "Choose your analysis model",
        ["Select a chart", "Bar chart", "Line chart", "Area chart"],
        index=0
    )

    if option != "Select a chart":
        st.subheader("📊 Detection Breakdown")

        if option == "Bar chart":
            st.bar_chart(df.set_index("Category"))

        elif option == "Line chart":
            st.line_chart(df.set_index("Category"))

        elif option == "Area chart":
            st.area_chart(df.set_index("Category"))

    with st.expander("View Raw Data"):
        st.json(stats)

    
    if "email_sent" not in st.session_state:
        send_email(end_url, label, score, stats)
        st.session_state["email_sent"] = True